version: 2
jobs:
  # Build & Deploy against development backend
  "build-dev":
	docker:
		- image: circleci/openjdk:7
	steps:
	    - run: git clone --branch dev-circleci https://github.com/topcoder-platform/tc-website-glue glue
		- run: git clone https://github.com/topcoder-platform/tc-website-shared shared
		- run: git clone https://github.com/topcoder-platform/tc-website-external-artifacts external-artifacts
		- checkout
		- run: ant -f move.xml package-topcoder
		- setup_remote_docker
		# Build of Docker image.
	    - run:
		  name: Installation of build dependencies.
		  command: |
			apk add --no-cache bash
			apk add --no-cache jq py-pip sudo perl curl
			sudo pip install awscli --upgrade  
		- run:
		  name: Building java and image
		  command:
			- ant -f move.xml package-topcoder
			- ./buildimage.sh DEV
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only: dev-circleci
